#include "input.h"
#include <string.h>
#include <stdlib.h>

int g_actions[ACTION_COUNT];
int g_actions_pressed[ACTION_COUNT];
int g_mouse_dx, g_mouse_dy;
int g_mouse_btn[3];
int g_quit           = 0;
int g_window_w       = 1280, g_window_h = 720;
int g_reload_shaders = 0;
int g_mouse_captured = 0;

static SDL_Window *s_win             = NULL;
static SDL_Cursor *s_invisible_cursor = NULL;
static int         s_skip_motion     = 0;   /* ignore next MOUSEMOTION after warp */

static SDL_Cursor *make_invisible_cursor(void) {
    uint8_t data[1] = {0}, mask[1] = {0};
    return SDL_CreateCursor(data, mask, 8, 1, 0, 0);
}

void input_capture_mouse(SDL_Window *win, int capture) {
    s_win            = win;
    g_mouse_captured = capture;
    SDL_SetRelativeMouseMode(capture ? SDL_TRUE : SDL_FALSE);
    if (!s_invisible_cursor) s_invisible_cursor = make_invisible_cursor();
    if (capture) {
        SDL_SetCursor(s_invisible_cursor);
        SDL_ShowCursor(SDL_ENABLE);
        /* warp to center now so cursor starts inside */
        SDL_WarpMouseInWindow(win, g_window_w / 2, g_window_h / 2);
        s_skip_motion = 1;
    } else {
        SDL_SetCursor(SDL_GetDefaultCursor());
    }
}

void input_begin_frame(void) {
    memset(g_actions_pressed, 0, sizeof(g_actions_pressed));
    memset(g_mouse_btn, 0, sizeof(g_mouse_btn));
    g_mouse_dx       = 0;
    g_mouse_dy       = 0;
    g_reload_shaders = 0;

    /* Keep cursor inside the window every frame (desktop only).
       On web, Pointer Lock handles confinement; warping would break delta reporting. */
#ifndef VOXEL_WEB
    if (g_mouse_captured && s_win) {
        SDL_WarpMouseInWindow(s_win, g_window_w / 2, g_window_h / 2);
        s_skip_motion = 1;
    }
#endif
}

void input_process_event(SDL_Event *e) {
    if (e->type == SDL_QUIT) { g_quit = 1; return; }

    if (e->type == SDL_WINDOWEVENT) {
        if (e->window.event == SDL_WINDOWEVENT_RESIZED) {
            g_window_w = e->window.data1;
            g_window_h = e->window.data2;
        }
        if (e->window.event == SDL_WINDOWEVENT_FOCUS_GAINED && g_mouse_captured)
            SDL_SetRelativeMouseMode(SDL_TRUE);
    }

    if (e->type == SDL_MOUSEMOTION && g_mouse_captured) {
        /* Skip the synthetic event generated by our own warp */
        if (s_skip_motion) { s_skip_motion = 0; return; }
        g_mouse_dx += e->motion.xrel;
        g_mouse_dy += e->motion.yrel;
    }

    if (e->type == SDL_MOUSEBUTTONDOWN && g_mouse_captured) {
        if (e->button.button == SDL_BUTTON_LEFT)   g_mouse_btn[0] = 1;
        if (e->button.button == SDL_BUTTON_MIDDLE) g_mouse_btn[1] = 1;
        if (e->button.button == SDL_BUTTON_RIGHT)  g_mouse_btn[2] = 1;
    }

    if (e->type == SDL_KEYDOWN || e->type == SDL_KEYUP) {
        int pressed = (e->type == SDL_KEYDOWN);
        SDL_Scancode sc = e->key.keysym.scancode;

        if (sc == SDL_SCANCODE_ESCAPE && pressed) { g_quit = 1; return; }
        if (sc == SDL_SCANCODE_R && pressed)        g_reload_shaders = 1;

#define MAP(scan, action) \
    if (sc == (scan)) { g_actions[action] = pressed; if(pressed) g_actions_pressed[action]=1; }

        MAP(SDL_SCANCODE_W,      ACTION_FORWARD)
        MAP(SDL_SCANCODE_S,      ACTION_BACK)
        MAP(SDL_SCANCODE_A,      ACTION_LEFT)
        MAP(SDL_SCANCODE_D,      ACTION_RIGHT)
        MAP(SDL_SCANCODE_SPACE,  ACTION_JUMP)
        MAP(SDL_SCANCODE_LSHIFT, ACTION_SPRINT)
        MAP(SDL_SCANCODE_1,      ACTION_SLOT_1)
        MAP(SDL_SCANCODE_2,      ACTION_SLOT_2)
        MAP(SDL_SCANCODE_3,      ACTION_SLOT_3)
        MAP(SDL_SCANCODE_4,      ACTION_SLOT_4)
        MAP(SDL_SCANCODE_5,      ACTION_SLOT_5)
        MAP(SDL_SCANCODE_6,      ACTION_SLOT_6)
        MAP(SDL_SCANCODE_7,      ACTION_SLOT_7)
        MAP(SDL_SCANCODE_8,      ACTION_SLOT_8)
        MAP(SDL_SCANCODE_9,      ACTION_SLOT_9)
#undef MAP
    }
}
